Fix some broken imports (#828)
* Fix imports

* Fix imports: ALL was changed to FETCH_ALL

This fixes:
SyntaxError: The requested module './request-message.js' does not provide an export named 'ALL'

* Fix import to avoid using internal file name (Address review comment)